---
title: "Welcome!"
output: html_document
---

### Arturo de la Cruz Libardi

------------------------------------------------------------------------

*Research Assistant in Health Data Science,*

*Department of Social & Environmental Health Research,*

*London School of Hygiene and Tropical Medicine*

------------------------------------------------------------------------

### Online Presence

[Arturo.de-la-Cruz-Libardi\@lshtm.ac.uk](mailto:Arturo.de-la-Cruz-Libardi@lshtm.ac.uk)\
[github AdlCruz](https://github.com/AdlCruz)\
[\@dlCruzArturo](https://twitter.com/dlCruzArturo)\

------------------------------------------------------------------------

### Past Projects

> **select local raster files and view them over a worldmap**\
> [raster_viewer](https://github.com/AdlCruz/raster_viewer) is enabled by Shiny and Leaflet.

> **rctapi + rctexplorer: R based interaction with clinicaltrials.gov online database**\
> [rctapi](https://github.com/AdlCruz/rctapi) - search filter and download records\
> [rctexplorer](https://github.com/AdlCruz/rctexplorer) - load data to R shiny app for interactive plotting and further exploration\

> *Have a look at an interactive demonstration*

```{r out.width="100%"}
knitr::include_url(url="https://player.vimeo.com/video/595343322?h=97da0c4bb5")
```

> **Student Dissertations**\
> MSc Health Data Science,\
> [Building and testing R tools to extract and explore data from the online database ClinicalTrials.gov](/assets/deanonlshtmdiss.pdf)\
> BSc Neuroscience,\
> [The Role of Dopamine and Dopamine Receptor Signalling in Basal Ganglia-Mediated Action Selection](/assets/lrpbsckcl.pdf)

------------------------------------------------------------------------

### Interests

-   Environmental Epidemiology
-   Air Quality Modelling for Health Applications
-   [R](R-page.md), Remote Sensing, Open Science, Free Software Principles, Science Fiction, Rational Optimism...

------------------------------------------------------------------------

### More About Me

Feel free to get in touch for a less formal introduction.

------------------------------------------------------------------------

### Testing shiny app embedding (from shinyapps.io into this .md document and then onto github.io)

```{r out.width="100%"}
knitr::include_app(url = "https://adlcruz.shinyapps.io/hipmapp/", height = "800px")
```
